name: Publish Maven Central

on:
  push:
    branches: [ Wenrh2004-patch-1 ]

jobs:
  publish-maven-central:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GPG Key
        run: |
          echo "${{ secrets.GPG_SECRET }}" | base64 --decode | gpg --import --batch

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish to the Maven Central Repository
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_profiles: 'deploy'
          maven_goals_phases: 'clean deploy'
          maven_args: '-DskipTests'
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
